### ISSUE TITLE
[feat]: vcpkg support

### ISSUE THREAD

**Issue by SHIINASAMA** [hggq/paozhu#2]
Hello! I must say, this library is excellent. Is there any plan to increase support for vcpkg? I think using vcpkg can reduce the cost of setting up the environment and manage dependencies better. 

I happen to have experience working with vcpkg, and I think it could be a valuable addition to the project. What are your thoughts on this?

**Comment by hggq** [comment]
Thank you very much for your attention. We really need talents in this field to improve the use of vcpkg under windows. If you have expertise in this field, you can submit a PR and I will do the merger here

**Comment by SHIINASAMA** [comment]
You mentioned windows, I assume you have the intention to port the project to windows. So, there are some issues that are currently hindering the project's windows port, which I found when I was building paozhu using msys2.

- The **fcntl** function and the **flock** structure are not present in the msys2 toolchain.
- Using some **too short macros** which causes redefinition with existing macros on windows.
- Using some data types that don't work well cross-platforms, such as **unsigned long int** and **unsigned long**. These standard variables are flawed when developing across platforms, because their actual size is limited by the platform. The current problem is that these variables are used in **BrotliDecoderDecompressStream** and **BrotliEncoderCompressStream** functions.

I have implemented vcpkg on **unix-like** systems, but it doesn't work well on windows due to the three limitations above, especially the first one.

**Comment by hggq** [comment]
> You mentioned windows, I assume you have the intention to port the project to windows. So, there are some issues that are currently hindering the project's windows port, which I found when I was building paozhu using msys2.
> 
>     * The **fcntl** function and the **flock** structure are not present in the msys2 toolchain.
> 
>     * Using some **too short macros** which causes redefinition with existing macros on windows.
> 
>     * Using some data types that don't work well cross-platforms, such as **unsigned long int** and **unsigned long**. These standard variables are flawed when developing across platforms, because their actual size is limited by the platform. The current problem is that these variables are used in **BrotliDecoderDecompressStream** and **BrotliEncoderCompressStream** functions.
> 
> 
> I have implemented vcpkg on **unix-like** systems, but it doesn't work well on windows due to the three limitations above, especially the first one.

I have updated code, thanks offer detailed information, but  I don't understand "Using some too short macros which causes redefinition with existing macros on windows.",  you need still more detailed information for this one

**Comment by SHIINASAMA** [comment]
I have modified the above mentioned problems in the pr #3.

**Comment by hggq** [comment]
> I have modified the above mentioned problems in the pr #3.

OK! Later, I will merge the PR code
